/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pq_Native */

#ifndef _Included_org_pq_Native
#define _Included_org_pq_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pq_Native
 * Method:    connect
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_connect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pq_Native
 * Method:    closeConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native_closeConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    connStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_connStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    resultStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_resultStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    connError
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_connError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    initByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_initByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_pq_Native
 * Method:    closeResult
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native_closeResult
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    prepare
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_prepare
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_pq_Native
 * Method:    describe
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_describe
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native
 * Method:    closeStatement
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_closeStatement
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native
 * Method:    execPrepared
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_execPrepared
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_pq_Native
 * Method:    sendQueryPrepared
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_sendQueryPrepared
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_pq_Native
 * Method:    fieldValue
 * Signature: (JIIJ)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native_fieldValue
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     org_pq_Native
 * Method:    fieldIsNull
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pq_Native_fieldIsNull
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    fieldOid
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_fieldOid
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_pq_Native
 * Method:    fieldFormat
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_fieldFormat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_pq_Native
 * Method:    fieldLength
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_fieldLength
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    nTuples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_nTuples
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    query
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_query
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native
 * Method:    sendQuery
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_sendQuery
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native
 * Method:    setChunkedRowsMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_setChunkedRowsMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_pq_Native
 * Method:    nColumns
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_nColumns
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    nParams
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_nParams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    paramOid
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_paramOid
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_pq_Native
 * Method:    getResult
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_getResult
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
