/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pq_Native */

#ifndef _Included_org_pq_Native
#define _Included_org_pq_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pq_Native
 * Method:    PQconnectdb
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_PQconnectdb
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pq_Native
 * Method:    PQconndefaults
 * Signature: ()[Lorg/pq/PQconninfoOption;
 */
JNIEXPORT jobjectArray JNICALL Java_org_pq_Native_PQconndefaults
  (JNIEnv *, jclass);

/*
 * Class:     org_pq_Native
 * Method:    PQconninfo
 * Signature: (J)[Lorg/pq/PQconninfoOption;
 */
JNIEXPORT jobjectArray JNICALL Java_org_pq_Native_PQconninfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQfinish
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native_PQfinish
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQreset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native_PQreset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQping
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_PQping
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pq_Native
 * Method:    PQdb
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQdb
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQuser
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQuser
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQpass
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQpass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQhost
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQhost
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQhostaddr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQhostaddr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQport
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQport
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQoptions
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQoptions
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
