/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pq_Native */

#ifndef _Included_org_pq_Native
#define _Included_org_pq_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pq_Native
 * Method:    PQconnectdb
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_PQconnectdb
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pq_Native
 * Method:    PQconndefaults
 * Signature: ()[Lorg/pq/PQconninfoOption;
 */
JNIEXPORT jobjectArray JNICALL Java_org_pq_Native_PQconndefaults
  (JNIEnv *, jclass);

/*
 * Class:     org_pq_Native
 * Method:    PQconninfo
 * Signature: (J)[Lorg/pq/PQconninfoOption;
 */
JNIEXPORT jobjectArray JNICALL Java_org_pq_Native_PQconninfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQfinish
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native_PQfinish
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQreset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native_PQreset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQping
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_PQping
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pq_Native
 * Method:    PQstatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_PQstatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQtransactionStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_PQtransactionStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQerrorMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQerrorMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQexec
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_PQexec
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native
 * Method:    PQresultStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_PQresultStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQresStatus
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQresStatus
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_pq_Native
 * Method:    PQresultErrorMessage
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQresultErrorMessage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQclear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native_PQclear
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQntuples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_PQntuples
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native
 * Method:    PQgetvalue
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_PQgetvalue
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    PQgetisnull
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pq_Native_PQgetisnull
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    PQgetlength
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_PQgetlength
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    getValue
 * Signature: (JII)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_pq_Native_getValue
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    getInt
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native_getInt
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    getString
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_getString
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    getBB
 * Signature: (JII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_pq_Native_getBB
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    getBytes
 * Signature: (JII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_pq_Native_getBytes
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native
 * Method:    getTuple
 * Signature: (JI)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_pq_Native_getTuple
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
