/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pq_Native2 */

#ifndef _Included_org_pq_Native2
#define _Included_org_pq_Native2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pq_Native2
 * Method:    connect
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_connect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pq_Native2
 * Method:    closeConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native2_closeConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    connStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_connStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    resStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_resStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    connError
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native2_connError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    initByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_initByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_pq_Native2
 * Method:    closeResult
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native2_closeResult
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    prepare
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_prepare
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_pq_Native2
 * Method:    describe
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_describe
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native2
 * Method:    closeStatement
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_closeStatement
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native2
 * Method:    serializePrepared
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_serializePrepared
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
