/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pq_Native */

#ifndef _Included_org_pq_Native
#define _Included_org_pq_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pq_Native
 * Method:    foobar
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native_foobar
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_pq_Native
 * Method:    connect
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native_connect
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
