/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pq_Native2 */

#ifndef _Included_org_pq_Native2
#define _Included_org_pq_Native2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pq_Native2
 * Method:    connect
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_connect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pq_Native2
 * Method:    closeConnection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native2_closeConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    connStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_connStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    resStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_resStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    connError
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_pq_Native2_connError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    initByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_initByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_pq_Native2
 * Method:    closeResult
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native2_closeResult
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    prepare
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_prepare
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     org_pq_Native2
 * Method:    describe
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_describe
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native2
 * Method:    closeStatement
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_closeStatement
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_pq_Native2
 * Method:    serializePrepared
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_serializePrepared
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    execPrepared
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_pq_Native2_execPrepared
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    resultInfo
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native2_resultInfo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    fieldValue
 * Signature: (JIIJ)V
 */
JNIEXPORT void JNICALL Java_org_pq_Native2_fieldValue
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     org_pq_Native2
 * Method:    fieldIsNull
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_org_pq_Native2_fieldIsNull
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native2
 * Method:    fieldOid
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_fieldOid
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_pq_Native2
 * Method:    fieldFormat
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_fieldFormat
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_pq_Native2
 * Method:    fieldLength
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_fieldLength
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_pq_Native2
 * Method:    nTuples
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_pq_Native2_nTuples
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
