name: Build on macOS
on: [push]

jobs:

  build2:
    name: windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PostgreSQL
      uses: ikalnytskyi/action-setup-postgres@v8
      with:
        postgresql-version: '15' # Specify your desired version
        # Other optional parameters:
        # username: ci
        # password: sw0rdfish
        # database: test
    - name: bar
      run: echo $PG_LIBDIR
      shell: bash
    - name: foo
      run: echo $PROGRAMFILES
      shell: bash
    - name: foo2
      run: dir C:/PROGRA~1/POSTGR~1/18/lib
    - name: foo3
      run: dir C:/PROGRA~1/POSTGR~1/18/include
      
  build:
    name: "Mac OS Build"
    runs-on: macos-15-intel # macos-26 macos-15-intel

    steps:
    - name: foo
      run: ls -l ${JAVA_HOME}include

    - name: Check out repository code
      uses: actions/checkout@v4 # Use actions/checkout@v4 (or a later version)

    - name: Update Homebrew and install a formula (e.g., GitHub CLI)
      run: |
        brew update
        brew install gh # Installs the GitHub CLI
      # Homebrew is located in the PATH, so 'brew' commands work directly

    - name: Install libpq
      run: |
        brew install libpq

    - name: compile
      run: |
        cd untitled && make

    - name: save file
      uses: actions/upload-artifact@v4
      with:
        name: the_lib
        path: untitled/libfoo.dylib
