name: Build on various systems
on: push

jobs:

  windows:

    strategy:
      matrix:
        opt:
          - image: windows-11-arm
            name: "Windows x64"
            msys: CLANGARM64
            env: clang-aarch64
          - image: windows-2025
            name: "Windows arm64"
            msys: CLANG64
            env: clang-x86_64

    runs-on: ${{ matrix.opt.image }}

    name: ${{ matrix.opt.name }}

    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Setup MSYS2 and MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.opt.msys }}
          install: >-
            make
            mingw-w64-${{ matrix.opt.env }}-libpqxx
            mingw-w64-${{ matrix.opt.env }}-gcc-compat

      - name: prepare files
        run: ./script/platform.sh
        shell: bash

      - name: Compile the project
        shell: msys2 {0}
        run: |
          g++ --version
          ./script/build-windows.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.opt.image }}
          path: "*.dll"
          if-no-files-found: error

  macos:

    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

    strategy:
      matrix:
        opt:
          - image: macos-15-intel
            name: "MacOS Intel"
            libpq: /usr/local/opt/libpq
          - image: macos-26
            name: "MacOS M1"
            libpq: /opt/homebrew/opt/libpq

    runs-on: ${{ matrix.opt.image }}

    name: ${{ matrix.opt.name }}

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install libpq
        run: |
          brew update
          brew install libpq@18

      - name: prepare files
        run: ./script/platform.sh
        shell: bash

      - name: Compile the project
        shell: bash
        run: |
          g++ --version
          LIBPQ=${{ matrix.opt.libpq }} ./script/build-macos.sh

      - run: ls -l .

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.opt.image }}
          path: "*.dylib"

  linux:

    strategy:
      matrix:
        opt:
          - image: ubuntu-24.04
            name: "Linux x64"
          - image: ubuntu-24.04-arm
            name: "Linux arm64"

    runs-on: ${{ matrix.opt.image }}

    name: ${{ matrix.opt.name }}

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install libpq
        run: |
          sudo apt update
          sudo apt install -y postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt update
          sudo apt install -y postgresql-client-18 libpq-dev

      - run: pg_config

      - name: prepare files
        run: ./script/platform.sh
        shell: bash

      - name: Compile the project
        shell: bash
        run: |
          g++ --version
          ./script/build-linux.sh

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.opt.image }}
          path: "*.so"
          if-no-files-found: error
