name: Build on various systems
on: push

env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

jobs:

  Windows-x64:
    name: Windows x64
    runs-on: windows-2025

    env:
      LIBPQ: "C:/PROGRA~1/POSTGR~1/18"

    steps:
      - run: pg_config
      - uses: actions/checkout@v4
      - name: MinGW
        uses: egor-tensin/setup-mingw@v3
        with:
          platform: x64
      # TODO: do we need this?
      # - name: PostgreSQL
      #   uses: ikalnytskyi/action-setup-postgres@v8
      #   with:
      #     postgresql-version: '15' # Specify your desired version
      #     # Other optional parameters:
      #     # username: ci
      #     # password: sw0rdfish
      #     # database: test
      - name: compile
        run: cd untitled && make LIBPQ_LIB=$(pg_config --libdir) LIBPQ_INC=$(pg_config --includedir)
        shell: bash

      - run: ls -l untitled
        shell: bash

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-x64
          path: untitled/*.lib

  macOS-Intel:
    name: "macOS Intel"
    runs-on: macos-15-intel

    env:
      LIBPQ: /usr/local/opt/libpq

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Homebrew & stuff
        run: |
          brew update
          brew install libpq

      - name: compile
        run: |
          cd untitled && make

      - run: ls -l untitled

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Intel
          path: untitled/*.lib

  macOS-arm64:
    name: "macOS arm64"
    runs-on: macos-26

    env:
      LIBPQ: /opt/homebrew/opt/libpq

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Homebrew & stuff
        run: |
          brew update
          brew install libpq

      - name: compile
        run: |
          cd untitled && make

      - run: ls -l untitled

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-arm64
          path: untitled/*.lib

  Linux-x64:
    name: "Linux x64"
    runs-on: ubuntu-24.04

    env:
      LIBPQ: /usr/lib

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install libpq
        run: |
          sudo apt update
          sudo apt install -y libpq-dev

      - run: pg_config

      - name: compile
        run: |
          cd untitled && make LIBPQ_LIB=$(pg_config --libdir) LIBPQ_INC=$(pg_config --includedir)

      - run: ls -l untitled

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x64
          path: untitled/*.lib
